from datetime import datetime
from typing import List, Optional, Any, Dict
from pydantic import BaseModel, Field, ConfigDict
from app.models.staging_event import StagingEventStatus


class AIEnhancedPayload(BaseModel):
    """Structured AI output generated by Gemini/OpenAI."""
    enhancedTitle: Optional[str] = Field(None, description="Catchy, high-energy title for VibeMyNight")
    catchyDescription: Optional[str] = Field(None, description="Engaging marketing description with clear value proposition")
    highlights: List[str] = Field(default_factory=list, description="Key venue/artist highlights")
    genreTags: List[str] = Field(default_factory=list, description="Categorization badges e.g. Garba, DJ Night")
    whatsAppTeaser: Optional[str] = Field(None, description="High-converting 1-line WhatsApp share text with emojis")
    seoKeywords: List[str] = Field(default_factory=list, description="High intent SEO keywords")


class RawExternalEvent(BaseModel):
    """Normalized input representation of an event fetched from an external source."""
    source: str = "showmates"
    source_event_id: str
    source_url: Optional[str] = None
    title: str
    description: Optional[str] = None
    poster_url: Optional[str] = None
    banner_url: Optional[str] = None
    event_start_date: Optional[str] = None
    event_end_date: Optional[str] = None
    start_time: Optional[str] = None
    end_time: Optional[str] = None
    venue_name: Optional[str] = None
    venue_address: Optional[str] = None
    city: Optional[str] = None
    state: Optional[str] = None
    min_ticket_price: Optional[float] = None
    max_ticket_price: Optional[float] = None
    currency: str = "INR"
    raw_payload: Optional[Dict[str, Any]] = None


class StagingEventUpdate(BaseModel):
    """Fields allowed to be edited by Admin before approving import."""
    title: Optional[str] = None
    description: Optional[str] = None
    enhanced_title: Optional[str] = None
    catchy_description: Optional[str] = None
    highlights: Optional[List[str]] = None
    genre_tags: Optional[List[str]] = None
    seo_keywords: Optional[List[str]] = None
    whatsapp_teaser: Optional[str] = None
    poster_url: Optional[str] = None
    banner_url: Optional[str] = None
    event_start_date: Optional[str] = None
    event_end_date: Optional[str] = None
    start_time: Optional[str] = None
    end_time: Optional[str] = None
    venue_name: Optional[str] = None
    venue_address: Optional[str] = None
    city: Optional[str] = None
    state: Optional[str] = None
    min_ticket_price: Optional[float] = None
    max_ticket_price: Optional[float] = None
    currency: Optional[str] = None
    status: Optional[StagingEventStatus] = None
    raw_payload: Optional[Dict[str, Any]] = None


class StagingEventResponse(BaseModel):
    """Complete staging event representation returned to API clients."""
    model_config = ConfigDict(from_attributes=True)

    id: int
    source: str
    source_event_id: str
    source_url: Optional[str] = None
    title: str
    description: Optional[str] = None
    enhanced_title: Optional[str] = None
    catchy_description: Optional[str] = None
    highlights: Optional[List[str]] = []
    genre_tags: Optional[List[str]] = []
    seo_keywords: Optional[List[str]] = []
    whatsapp_teaser: Optional[str] = None
    poster_url: Optional[str] = None
    banner_url: Optional[str] = None
    event_start_date: Optional[str] = None
    event_end_date: Optional[str] = None
    start_time: Optional[str] = None
    end_time: Optional[str] = None
    venue_name: Optional[str] = None
    venue_address: Optional[str] = None
    city: Optional[str] = None
    state: Optional[str] = None
    min_ticket_price: Optional[float] = None
    max_ticket_price: Optional[float] = None
    currency: str = "INR"
    status: StagingEventStatus
    duplicate_of: Optional[int] = None
    ai_processed: bool
    ai_provider: Optional[str] = None
    ai_model: Optional[str] = None
    ai_error: Optional[str] = None
    raw_payload: Optional[Dict[str, Any]] = None
    created_at: datetime
    updated_at: datetime


class StagingEventListResponse(BaseModel):
    """Paginated list of staged events."""
    items: List[StagingEventResponse]
    total: int
    page: int
    page_size: int
    total_pages: int


class SyncFetchResponse(BaseModel):
    """Response returned after running the sync and ingestion cycle."""
    success: bool
    fetched: int
    processed: int
    duplicates: int
    failed: int
    message: Optional[str] = None


# =========================================================================
# UNIVERSAL LIVE DISCOVERY & DEEP SCRAPING SCHEMAS
# =========================================================================

class DiscoverEventsRequest(BaseModel):
    """Request payload for live catalog discovery."""
    source: str = Field("all", description="Source: 'all', 'showmates', 'bookmyshow', 'district'")
    city: Optional[str] = Field(None, description="City name or 'ALL'")
    category: Optional[str] = Field(None, description="Category filter e.g. 'Garba', 'Music'")
    page: int = Field(1, ge=1, description="Catalog page number")
    pageSize: int = Field(20, ge=1, le=100, description="Items per page")


class DiscoveredEventItem(BaseModel):
    """Lightweight discovery summary item."""
    source: str
    source_event_id: str
    title: str
    event_url: str
    poster_url: Optional[str] = None
    banner_url: Optional[str] = None
    venue_name: Optional[str] = None
    city: Optional[str] = None
    event_start_date: Optional[str] = None
    event_end_date: Optional[str] = None
    starting_price: Optional[float] = None
    currency: str = "INR"
    category: Optional[str] = None
    is_already_staged: bool = False
    is_already_in_production: bool = False
    discovered_at: Optional[str] = None
    raw_discovery_payload: Optional[Dict[str, Any]] = None


class DiscoverEventsResponse(BaseModel):
    """Response returned by live catalog discovery."""
    success: bool
    source: str
    city: Optional[str] = None
    category: Optional[str] = None
    total_discovered: int
    items: List[DiscoveredEventItem]
    timestamp: str


class DeepScrapeSelectedTarget(BaseModel):
    """Target event to deep scrape."""
    source: str
    source_event_id: str
    event_url: str
    title: Optional[str] = None
    hint_payload: Optional[Dict[str, Any]] = None


class DeepScrapeRequest(BaseModel):
    """Admin request to deep scrape selected events."""
    events: List[DeepScrapeSelectedTarget]
    run_ai_enrichment: bool = True


class DeepScrapeResultItem(BaseModel):
    """Individual deep scrape result item."""
    source: str
    source_event_id: str
    staging_id: Optional[int] = None
    title: str
    status: str
    validation_status: str
    is_duplicate: bool = False
    duplicate_of: Optional[int] = None
    message: Optional[str] = None


class DeepScrapeResponse(BaseModel):
    """Summary response from deep scraping selected events."""
    success: bool
    total_requested: int
    total_staged: int
    total_duplicates: int
    total_failed: int
    results: List[DeepScrapeResultItem]
    message: str
